/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package savr;
import savr.ryan.tools.RDynamicUI;
import com.ryansheridan.rfields.RTextField;
import com.formdev.flatlaf.FlatDarkLaf;
import com.kitfox.svg.app.beans.SVGPanel;
import com.savrui.components.AgricultureUIManager;
import com.savrui.components.FoodStockAppManager;
import com.savrui.components.RWasteManagementController;
import java.awt.Color;
import com.savrui.components.RButton;
import com.savrui.components.RFadePanel;
import com.savrui.components.RGlassDialog;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import savr.ryan.tools.RDynamicUI.Theme;
import static savr.ryan.tools.RDynamicUI.Theme.DARK;
import static savr.ryan.tools.RDynamicUI.Theme.LIGHT;
import savr.ryan.tools.RDataPersistence;
import savr.ryan.tools.RDatabaseORM;
import savr.sean.AgricultureUI;

/**
 *
 * @author ryan
 */
public class MainApplication extends javax.swing.JFrame {
    
    /**
     * Creates new form ZeroHungerApp
     */
    public MainApplication() {
        initComponents();
        
        RDataPersistence r = RDataPersistence.getInstance();
        
        Theme t = RDataPersistence.getTheme();
        
        if(t == LIGHT) {
            rToggle1.setSelected(true);
            rToggle1.repaint();
        }
        
        RDynamicUI.updateFont(this.getContentPane());
        
        setBackground(jPanel2.getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fadePanelButton = new com.savrui.components.RFadePanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new RButton();
        jButton2 = new RButton();
        jButton3 = new RButton();
        rButton6 = new com.savrui.components.RButton();
        fadePanelSettings = new com.savrui.components.RFadePanel();
        rButton7 = new com.savrui.components.RButton();
        jPanel5 = new javax.swing.JPanel();
        rToggle1 = new com.savrui.components.RToggle();
        jLabel4 = new javax.swing.JLabel();
        rFadePanel2 = new com.savrui.components.RFadePanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rLogoPanel1 = new savr.ConorLogoPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        jPanel2.setLayout(new java.awt.CardLayout());

        jButton1.setText("Waste Management UI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Food Stock UI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agriculture Aid UI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        rButton6.setButtonType(com.savrui.components.RButton.ButtonType.SETTINGS);
        rButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fadePanelButtonLayout = new javax.swing.GroupLayout(fadePanelButton);
        fadePanelButton.setLayout(fadePanelButtonLayout);
        fadePanelButtonLayout.setHorizontalGroup(
            fadePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fadePanelButtonLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(fadePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fadePanelButtonLayout.createSequentialGroup()
                        .addComponent(rButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fadePanelButtonLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        fadePanelButtonLayout.setVerticalGroup(
            fadePanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fadePanelButtonLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(rButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(fadePanelButton, "card2");

        rButton7.setButtonType(com.savrui.components.RButton.ButtonType.HOME);
        rButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButton7ActionPerformed(evt);
            }
        });

        rToggle1.setText("rToggle1");
        rToggle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rToggle1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Toggle Theme");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(rToggle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rToggle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        javax.swing.GroupLayout fadePanelSettingsLayout = new javax.swing.GroupLayout(fadePanelSettings);
        fadePanelSettings.setLayout(fadePanelSettingsLayout);
        fadePanelSettingsLayout.setHorizontalGroup(
            fadePanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fadePanelSettingsLayout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(rButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(fadePanelSettingsLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fadePanelSettingsLayout.setVerticalGroup(
            fadePanelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fadePanelSettingsLayout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(rButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(fadePanelSettings, "card3");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Food waste management system");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Savr");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(rLogoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(rLogoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rFadePanel2Layout = new javax.swing.GroupLayout(rFadePanel2);
        rFadePanel2.setLayout(rFadePanel2Layout);
        rFadePanel2Layout.setHorizontalGroup(
            rFadePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rFadePanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rFadePanel2Layout.setVerticalGroup(
            rFadePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rFadePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(rFadePanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JFrame newFrame;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RWasteManagementController controllerPanel = new RWasteManagementController();
        
        newFrame = new JFrame("Waste Management Controller");
        newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newFrame.setSize(controllerPanel.getPreferredSize());
        newFrame.add(controllerPanel); 
        newFrame.setLocationRelativeTo(null);
        newFrame.setVisible(true); 

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //button will open the foodstockapp jframe
        FoodStockAppManager FoodStockMenu = new FoodStockAppManager();
        
        newFrame = new JFrame("Food Stock App");
        newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newFrame.setSize(800,600);
        newFrame.add(FoodStockMenu);
        newFrame.setLocationRelativeTo(null);
        newFrame.setVisible(true);
        //make the logopanel be the tab to show up when coming on the food stock app
        FoodStockMenu.logoPanel.setVisible(true);
        FoodStockMenu.foodStockPanel.setVisible(false);
        FoodStockMenu.viewingStockPanel.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*
           Agriculture Aid JFrame
        */


        AgricultureUIManager agriUIManager = new AgricultureUIManager();

        newFrame = new JFrame("Agricultural Aid Manager");
        newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        newFrame.setSize(800, 640);
        newFrame.add(agriUIManager); 
        newFrame.setLocationRelativeTo(null);
        newFrame.setVisible(true); 

        agriUIManager.createCorpDonorPanel.setVisible(true);
        agriUIManager.createItemDetailsPanel.setVisible(true);
        agriUIManager.createDonorTitlePanel.setVisible(true);
        agriUIManager.createEmptyPanel.setVisible(true);
        agriUIManager.donorTypeSelectorPanel.setVisible(true);
        agriUIManager.corpSelectorBTN.setEnabled(true);
        
        agriUIManager.viewItemDetailsPanel.setVisible(false);
        agriUIManager.viewDonorTypeSelectorPanel.setVisible(false);
        agriUIManager.viewDonorTypePanel.setVisible(false);
        agriUIManager.viewSearchPanel.setVisible(false);
        
        agriUIManager.displayTA.setVisible(false);
        agriUIManager.displayDonorBTN.setVisible(false);
        
        agriUIManager.createIndiDonorPanel.setVisible(false);

        agriUIManager.menuCreateDonoLBL.setForeground(new Color(255,255,200));
        
        AgricultureUI.addTempRecords();
        //AgricultureUI.loadAgri();
        //AgricultureUI.saveAgri();
        AgricultureUI.mkFile();

        this.dispose();
        
        //AgricultureUIManager agriUIManager = new AgricultureUIManager();

        //JFrame newFrame = new JFrame("Agricultural Aid Manager");
        //newFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //newFrame.setSize(800, 600);
        //newFrame.add(agriUIManager); 
        //newFrame.setVisible(true); 

        //this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButton6ActionPerformed
        fadePanelButton.setFadeCompleteListener(new RFadePanel.FadeCompleteListener() {
            @Override
            public void onFadeComplete(boolean fadedOut) {
                if (fadedOut) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            fadePanelButton.setVisible(false);
                            fadePanelSettings.fadeIn();
                        }
                    });
                }
            }
        });
        
        fadePanelButton.fadeOut();
    }//GEN-LAST:event_rButton6ActionPerformed

    private void rButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButton7ActionPerformed
        // if we have updated our theme
        if(updated) {
            displayRefreshDialog(evt);
            
            return;
        }
        
        fadePanelSettings.setFadeCompleteListener(new RFadePanel.FadeCompleteListener() {
            @Override
            public void onFadeComplete(boolean fadedOut) {
                if (fadedOut) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            fadePanelSettings.setVisible(false);
                            fadePanelButton.fadeIn();
                        }
                    });
                }
            }
        });

        fadePanelSettings.fadeOut();
    }//GEN-LAST:event_rButton7ActionPerformed

    private boolean updated = false;
    
    private void rToggle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rToggle1ActionPerformed
        // TODO add your handling code here:
        RDynamicUI uiManager = RDynamicUI.getInstance();
        
        updated = !updated;
        System.out.println(updated);
        if (rToggle1.isSelected()) {
            RDataPersistence.saveTheme(LIGHT);
            uiManager.applyTheme(LIGHT);
        } else {
            RDataPersistence.saveTheme(DARK);
            uiManager.applyTheme(DARK);
        }
    }//GEN-LAST:event_rToggle1ActionPerformed

    public void displayRefreshDialog(java.awt.event.ActionEvent evt) {
        // create a RGlassDialog, set primary button and secondary button text
        RGlassDialog glassPanel = new RGlassDialog("Refresh", "Dismiss") {
            // we can override submitPress to make it do something when submit is pressed
            @Override
            public void submitPress() {
                super.submitPress();
                // stolen from sean, thanks sean
                MainApplication zerohunger = new MainApplication();
                zerohunger.setLocationRelativeTo(null);
                zerohunger.setVisible(true);

                Window pFrame = SwingUtilities.getWindowAncestor(this);
                if(pFrame !=null){
                    pFrame.dispose();
                }
            }
            
            @Override
            public void dismissPress() {
                super.dismissPress();
                // toggle button back to original state
                rToggle1.setSelected(!rToggle1.isSelected());
                rToggle1.repaint();

                updated = !updated;
            }
        };

        // the little box inside the RGlassDialog will have some text we can set
        glassPanel.setTitle("The application needs to be refreshed to save changes!");
        
        // allow our RGlassDialog to fade in
        // pass it the object that triggered the event, we can get the parent
        // of this object which will be the JFrame, then we can set the GlassPane
        // of JFrame to RGlassDialog
        glassPanel.fadeInOver((Component) evt.getSource());
    }
    
    @Override 
    public void setVisible(boolean b) {
        rFadePanel2.setOpacity(0f);
        rFadePanel2.fadeIn();
        super.setVisible(b);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FontFormatException, IOException {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        RDynamicUI uiManager = RDynamicUI.getInstance();
        uiManager.applyTheme(RDataPersistence.getTheme());
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // line for window centering
                MainApplication mainApplication = new MainApplication();
                
                mainApplication.setTitle("Savr");
                
                mainApplication.setLocationRelativeTo(null);
                mainApplication.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.savrui.components.RFadePanel fadePanelButton;
    private com.savrui.components.RFadePanel fadePanelSettings;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private com.savrui.components.RButton rButton6;
    private com.savrui.components.RButton rButton7;
    private com.savrui.components.RFadePanel rFadePanel2;
    private savr.ConorLogoPanel rLogoPanel1;
    private com.savrui.components.RToggle rToggle1;
    // End of variables declaration//GEN-END:variables
}
