/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package savr;
import com.ryansheridan.rfields.RTextField;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ryan
 */
public class ZeroHungerApp extends javax.swing.JFrame {

    /**
     * Creates new form ZeroHungerApp
     */
    public ZeroHungerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rCardView2 = new com.savrui.components.RCardView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rCardView2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rCardView2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FontFormatException, IOException {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            javax.swing.UIManager.put("Panel.background", new Color(30, 30, 30));
            javax.swing.UIManager.put("Button.background", new Color(60, 60, 60));
            javax.swing.UIManager.put("Button.foreground", Color.WHITE);
            javax.swing.UIManager.put("TextField.background", new Color(40, 40, 40));
            javax.swing.UIManager.put("TextField.foreground", Color.WHITE);
            javax.swing.UIManager.put("TextField.caretForeground", Color.WHITE);
            javax.swing.UIManager.put("Label.foreground", Color.WHITE);
            javax.swing.UIManager.put("TextArea.background", new Color(40, 40, 40));
            javax.swing.UIManager.put("TextArea.foreground", Color.WHITE);
            javax.swing.UIManager.put("ComboBox.background", new Color(40, 40, 40));
            javax.swing.UIManager.put("ComboBox.foreground", Color.WHITE);
            javax.swing.UIManager.put("ComboBox.selectionBackground", new Color(60, 60, 60));
            javax.swing.UIManager.put("ComboBox.selectionForeground", Color.WHITE);
            
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());

        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Font ubuntuFont = null;
                try {
                    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                    Font f = Font.createFont(Font.TRUETYPE_FONT, getClass().getResourceAsStream("/resources/Ubuntu-Regular.ttf"));
                    if (!ge.registerFont(f)) {
                        System.out.println("Unable to register font");
                    }
                    ubuntuFont = f.deriveFont(Font.PLAIN, 17);
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (FontFormatException e) {
                    e.printStackTrace();
                }

                // Set the font for all components
                UIManager.put("Label.font", ubuntuFont);
                UIManager.put("Button.font", ubuntuFont);
                UIManager.put("TextField.font", ubuntuFont);
                UIManager.put("PasswordField.font", ubuntuFont);
                UIManager.put("TextArea.font", ubuntuFont);
                UIManager.put("ComboBox.font", ubuntuFont);
                UIManager.put("CheckBox.font", ubuntuFont);
                UIManager.put("RadioButton.font", ubuntuFont);
                UIManager.put("TabbedPane.font", ubuntuFont);
                UIManager.put("Table.font", ubuntuFont);
                UIManager.put("ToolTip.font", ubuntuFont);
                new ZeroHungerApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.savrui.components.RCardView rCardView2;
    // End of variables declaration//GEN-END:variables
}
