/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.savrui.components;

import com.ryansheridan.rfields.RTextField;
import java.awt.Component;
import java.awt.Window;
import java.util.Arrays;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import savr.MainApplication;
import savr.ryan.FoodSaver;
import savr.ryan.RedistributionRecord;
import savr.ryan.WasteSource;
import savr.ryan.WasteSource.SourceType;
import savr.ryan.tools.interfaces.RInformationPanelEditor;

/**
 *
 * @author ryan
 */
public class RWasteSourceController extends javax.swing.JPanel implements RInformationPanelEditor {

    /**
     * Creates new form RWasteSourceController
     */
    public RWasteSourceController() {
        initComponents();
        
        sourceEdit.fadeIn();
        rScrollView1.setRInformationPanelEditor(this);
    }


    public void setSourceAddressField(String text) {
        sourceAddressField.setText(text);
    }
    
    private WasteSource selectedSource;
    private FoodSaver selectedFoodSaver;
    private RedistributionRecord selectedRecord;

    public WasteSource getSelectedSource() {
        return selectedSource;
    }

    public void setSelectedSource(WasteSource selectedSource) {
        this.selectedSource = selectedSource;
        
    }

    public FoodSaver getSelectedFoodSaver() {
        return selectedFoodSaver;
    }

    public void setSelectedFoodSaver(FoodSaver selectedFoodSaver) {
        this.selectedFoodSaver = selectedFoodSaver;
    }

    public RedistributionRecord getSelectedRecord() {
        return selectedRecord;
    }

    public void setSelectedRecord(RedistributionRecord selectedRecord) {
        this.selectedRecord = selectedRecord;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rTextField1 = new com.ryansheridan.rfields.RTextField();
        rButton5 = new com.savrui.components.RButton();
        rButton3 = new com.savrui.components.RButton();
        rButton6 = new com.savrui.components.RButton();
        rScrollView1 = new com.savrui.components.RScrollView();
        jPanel1 = new javax.swing.JPanel();
        sourceEdit = new com.savrui.components.RFadePanel();
        sourceAddressField = new com.ryansheridan.rfields.RTextField();
        sourceNameField = new com.ryansheridan.rfields.RTextField();
        sourceWasteAmountField = new com.ryansheridan.rfields.RTextField();
        selectedIdLabel = new javax.swing.JLabel();
        sourceFieldTypeCombo = new javax.swing.JComboBox<>();
        rButton2 = new com.savrui.components.RButton();
        submitEdit = new com.savrui.components.RButton();
        jLabel2 = new javax.swing.JLabel();
        rButton1 = new com.savrui.components.RButton();

        rTextField1.setBackground(new java.awt.Color(50, 50, 50));
        rTextField1.setBorderBottom(false);
        rTextField1.setBottomLeftRadius(10);
        rTextField1.setBottomRightRadius(10);
        rTextField1.setPlaceholder("Search Source");
        rTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTextField1ActionPerformed(evt);
            }
        });

        rButton5.setText("Import Data");
        rButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButton5ActionPerformed(evt);
            }
        });

        rButton3.setBackground(new java.awt.Color(16, 121, 234));
        rButton3.setText("Export Data");
        rButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButton3ActionPerformed(evt);
            }
        });

        rButton6.setButtonType(com.savrui.components.RButton.ButtonType.HOME);
        rButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButton6ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        sourceEdit.setOpacity(0f);
        sourceEdit.setVisible(false);

        sourceAddressField.setFieldType(com.ryansheridan.rfields.RTextField.FieldType.ANY);
        sourceAddressField.setPlaceholder("Country / Location");
        sourceAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceAddressFieldActionPerformed(evt);
            }
        });

        sourceNameField.setPlaceholder("Name");

        sourceWasteAmountField.setFieldType(com.ryansheridan.rfields.RTextField.FieldType.ANY);
        sourceWasteAmountField.setPlaceholder("Waste Amount");

        selectedIdLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        selectedIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedIdLabel.setText("Selected: None");
        selectedIdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        sourceFieldTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saver Type", "INDIVIDUAL", "ORGANISATION", "FARMER", "RETAILER", " " }));

        rButton2.setBackground(new java.awt.Color(34, 197, 94));
        rButton2.setText("Create New");

        submitEdit.setBackground(new java.awt.Color(34, 197, 94));
        submitEdit.setText("Submit Edit");
        submitEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Make an edit");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout sourceEditLayout = new javax.swing.GroupLayout(sourceEdit);
        sourceEdit.setLayout(sourceEditLayout);
        sourceEditLayout.setHorizontalGroup(
            sourceEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sourceNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sourceWasteAmountField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sourceAddressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(selectedIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
            .addComponent(sourceFieldTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(submitEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sourceEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sourceEditLayout.setVerticalGroup(
            sourceEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sourceEditLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceWasteAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourceFieldTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
        );

        jPanel1.add(sourceEdit, "card3");

        rButton1.setText("Delete Selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rScrollView1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(rTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rScrollView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rTextField1ActionPerformed

    private void rButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButton3ActionPerformed

    private void rButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButton6ActionPerformed
        // thanks sean
        MainApplication zerohunger = new MainApplication();
        zerohunger.setVisible(true);
        zerohunger.setLocationRelativeTo(null);
        
        Window pFrame = SwingUtilities.getWindowAncestor(this);
        if(pFrame !=null){
            pFrame.dispose();
        }
    }//GEN-LAST:event_rButton6ActionPerformed

    private void rButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButton5ActionPerformed

    private void submitEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitEditActionPerformed

    private void sourceAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceAddressFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.savrui.components.RButton rButton1;
    private com.savrui.components.RButton rButton2;
    private com.savrui.components.RButton rButton3;
    private com.savrui.components.RButton rButton5;
    private com.savrui.components.RButton rButton6;
    private com.savrui.components.RScrollView rScrollView1;
    private com.ryansheridan.rfields.RTextField rTextField1;
    private javax.swing.JLabel selectedIdLabel;
    private com.ryansheridan.rfields.RTextField sourceAddressField;
    private com.savrui.components.RFadePanel sourceEdit;
    private javax.swing.JComboBox<String> sourceFieldTypeCombo;
    private com.ryansheridan.rfields.RTextField sourceNameField;
    private com.ryansheridan.rfields.RTextField sourceWasteAmountField;
    private com.savrui.components.RButton submitEdit;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateSourceNameField(String text) {
        sourceNameField.setText(text);
    }

    @Override
    public void updateSourceAddressField(String text) {
       sourceAddressField.setText(text);
    }

    @Override
    public void updateWasteAmountField(String text) {
        sourceWasteAmountField.setText(text);
    }

    @Override
    public void clearInformationPanel() {
        updateSourceNameField("");
        updateSourceAddressField("");
        updateWasteAmountField("");
        updateSourceTypeCombo("Saver Type");
    }

    @Override
    public void updateSourceTypeCombo(String text) {
        sourceFieldTypeCombo.setSelectedItem(text);
    }

    @Override
    public void updateSelectedId(String id) {
        selectedIdLabel.setText(String.format("Selected: %d", id));
    }
}
