/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.savrui.components;

import savr.ryan.tools.RDynamicUI;

/**
 *
 * @author ryan
 */
public class RWasteManagementController extends javax.swing.JPanel {

    /**
     * Creates new form RWasteManagementController
     */
    public RWasteManagementController() {
        initComponents();
        RDynamicUI.updateFont(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        rWasteSourceController1 = new com.savrui.components.RWasteSourceController();
        rFoodSaverController1 = new com.savrui.components.RFoodSaverController();
        rRedistributionController1 = new com.savrui.components.RRedistributionController();

        jTabbedPane1.addTab("Waste Source Controller", rWasteSourceController1);
        jTabbedPane1.addTab("Food Saver Controller", rFoodSaverController1);
        jTabbedPane1.addTab("Redistribution", rRedistributionController1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.savrui.components.RFoodSaverController rFoodSaverController1;
    private com.savrui.components.RRedistributionController rRedistributionController1;
    private com.savrui.components.RWasteSourceController rWasteSourceController1;
    // End of variables declaration//GEN-END:variables
}
